services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.gui
    ports:
      - "5000:5000"
  
    networks:
      - model-net

  gui:
    build:
      context: .
      dockerfile: Dockerfile.gui
    ports:
      - "8501:8501"
    networks:
      - model-net
    depends_on:
      - api

networks:
  model-net:
    driver: bridge

